FROM postgres:15-alpine

# Configurar variables de entorno
ENV POSTGRES_DB=cldc_database
ENV POSTGRES_USER=cldc_user
ENV POSTGRES_PASSWORD=cldc_password
ENV PGDATA=/var/lib/postgresql/data/pgdata

# Crear directorio de datos
RUN mkdir -p /var/lib/postgresql/data/pgdata
RUN chown -R postgres:postgres /var/lib/postgresql/data

# Exponer puerto
EXPOSE 5432

# Comando de inicio
CMD ["postgres"]
