version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cldc_app
    container_name: cldc_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cldc_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: cldc_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cldc_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: cldc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cldc_database
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: cldc_user
      MYSQL_PASSWORD: cldc_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - cldc_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cldc_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - cldc_network
    depends_on:
      - db

volumes:
  db_data:
    driver: local

networks:
  cldc_network:
    driver: bridge