services:
  - type: web
    name: app-cldc
    env: docker
    dockerfilePath: ./Dockerfile.render
    buildCommand: |
      echo "Build process handled by Dockerfile"
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
