services:
  - type: web
    name: app-cldc
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: |
      echo "Build process handled by Dockerfile"
    startCommand: /start.sh
    plan: starter
    region: oregon
    database:
      name: cldc-database
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:rRndXzwA9CalgmcCg7aFarcIIHlMjklEqgXS08aM3sU=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cldc-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cldc-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cldc-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cldc-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cldc-database
          property: password
      - key: CACHE_DRIVER
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: MAIL_MAILER
        value: log
      - key: BROADCAST_DRIVER
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: VITE_APP_NAME
        value: "${APP_NAME}"
      - key: VITE_APP_ENV
        value: "${APP_ENV}"
      - key: VITE_APP_URL
        value: "${APP_URL}"

  - type: pserv
    name: cldc-database
    plan: starter
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: cldc_database
      - key: POSTGRES_USER
        value: cldc_user
      - key: POSTGRES_PASSWORD
        value: cldc_password
      - key: PGDATA
        value: /var/lib/postgresql/data/pgdata